In [1]:
import pandas as pd
import numpy as np

In [2]:
h1b= pd.read_excel("H1B_Data_FY2023_Q4.xlsx")

In [3]:
h1b.head()

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL
0,I-200-23244-317261,Certified - Withdrawn,2023-09-01,2023-09-30,2023-09-11,H-1B,"Analyst, Business Sr",15-2031.00,Operations Research Analysts,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
1,I-202-23242-306442,Certified - Withdrawn,2023-08-30,2023-09-30,2023-09-07,H-1B1 Singapore,Board Certified Behavior Analyst,19-3034.00,School Psychologists,Y,...,NaN,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
2,I-200-23242-308144,Certified - Withdrawn,2023-08-30,2023-09-30,2023-09-07,H-1B,Manager - Software Engineering,15-1252.00,Software Developers,Y,...,No,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,Sheppard,Kaitlyn (11606.425.22),NaN,Berry Appleman & Leiden LLP,ksheppard@bal.com
3,I-200-23172-131625,Certified - Withdrawn,2023-06-21,2023-09-30,2023-06-28,H-1B,SOFTWARE DEVELOPER,15-1252.00,Software Developers,Y,...,No,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
4,I-200-23170-125146,Certified - Withdrawn,2023-06-19,2023-09-30,2023-06-26,H-1B,SOFTWARE DEVELOPER,15-1252.00,Software Developers,Y,...,No,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN

In [4]:
h1b.shape

(127939, 96)

## Dropping irrelevant columns based on either their value types or redundancy

In [5]:
columns_to_drop = ['CASE_NUMBER', 'JOB_TITLE', 'TRADE_NAME_DBA', 'EMPLOYER_NAME',
       'TRADE_NAME_DBA', 'EMPLOYER_ADDRESS1', 'EMPLOYER_ADDRESS2',
       'EMPLOYER_CITY','EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', 'EMPLOYER_PHONE',
       'EMPLOYER_PHONE_EXT', 'AGENT_ATTORNEY_LAST_NAME', 'AGENT_ATTORNEY_FIRST_NAME',
       'AGENT_ATTORNEY_MIDDLE_NAME', 'AGENT_ATTORNEY_ADDRESS1',
       'AGENT_ATTORNEY_ADDRESS2', 'AGENT_ATTORNEY_CITY',
       'AGENT_ATTORNEY_STATE', 'AGENT_ATTORNEY_POSTAL_CODE',
       'AGENT_ATTORNEY_COUNTRY', 'AGENT_ATTORNEY_PROVINCE',
       'AGENT_ATTORNEY_PHONE', 'AGENT_ATTORNEY_PHONE_EXT',
       'AGENT_ATTORNEY_EMAIL_ADDRESS', 'LAWFIRM_NAME_BUSINESS_NAME',
       'STATE_OF_HIGHEST_COURT', 'NAME_OF_HIGHEST_STATE_COURT',
       'WORKSITE_WORKERS',
       'SECONDARY_ENTITY_BUSINESS_NAME', 'WORKSITE_ADDRESS1',
       'WORKSITE_ADDRESS2', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_POSTAL_CODE', 'WAGE_RATE_OF_PAY_FROM',
       'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY', 'PREPARER_LAST_NAME',
       'PREPARER_FIRST_NAME', 'PREPARER_MIDDLE_INITIAL',
       'PREPARER_BUSINESS_NAME', 'PREPARER_EMAIL', 'EMPLOYER_POC_LAST_NAME',
       'EMPLOYER_POC_FIRST_NAME', 'EMPLOYER_POC_MIDDLE_NAME',
       'EMPLOYER_POC_JOB_TITLE', 'EMPLOYER_POC_ADDRESS1',
       'EMPLOYER_POC_ADDRESS2', 'EMPLOYER_POC_CITY', 'EMPLOYER_POC_STATE',
       'EMPLOYER_POC_POSTAL_CODE', 'EMPLOYER_POC_COUNTRY',
       'EMPLOYER_POC_PROVINCE', 'EMPLOYER_POC_PHONE', 'EMPLOYER_POC_PHONE_EXT',
       'EMPLOYER_POC_EMAIL']

In [6]:
h1b_filtered = h1b.drop(columns=columns_to_drop,axis=1)

## columns with a lot of nulls  can also be dropped since they are redundant

In [8]:

redundant_columns = ['ORIGINAL_CERT_DATE','PW_TRACKING_NUMBER','PW_OTHER_SOURCE','PW_OTHER_YEAR','PW_SURVEY_PUBLISHER','PW_SURVEY_NAME','WILLFUL_VIOLATOR', 'SUPPORT_H1B','STATUTORY_BASIS','APPENDIX_A_ATTACHED']

In [9]:
h1b_filtered = h1b_filtered.drop(columns=redundant_columns,axis=1)

# SOC_TITLE gives a broader idea of the job title.However,one title i.e. software engineer appears a very high amount of times. Due to this, we can filter our data based on the value counts of each title. A good idea could be to consider only the titles that have a value count between 100 - 10000

In [41]:
df = h1b_filtered[(h1b_filtered['SOC_TITLE'].map(h1b_filtered['SOC_TITLE'].value_counts()>100)) & (h1b_filtered['SOC_TITLE'].map(h1b_filtered['SOC_TITLE'].value_counts()<10000))]

In [42]:
df

,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,BEGIN_DATE,END_DATE,...,PW_SURVEY_PUBLISHER,PW_SURVEY_NAME,TOTAL_WORKSITE_LOCATIONS,AGREE_TO_LC_STATEMENT,H_1B_DEPENDENT,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE
0,Certified - Withdrawn,2023-09-01,2023-09-30,2023-09-11,H-1B,15-2031.00,Operations Research Analysts,Y,2024-03-01,2027-02-28,...,NaN,NaN,1,Yes,No,No,NaN,NaN,NaN,Disclose Business
6,Certified - Withdrawn,2023-02-15,2023-09-30,2023-02-22,H-1B,13-1111.00,Management Analysts,Y,2023-02-15,2024-06-11,...,NaN,NaN,2,Yes,No,No,NaN,NaN,NaN,Disclose Business
7,Certified - Withdrawn,2022-11-29,2023-09-30,2022-12-06,E-3 Australian,11-3021.00,Computer and Information Systems Managers,Y,2023-01-01,2024-12-31,...,NaN,NaN,1,Yes,NaN,NaN,NaN,NaN,NaN,Disclose Business
8,Certified - Withdrawn,2022-08-03,2023-09-30,2022-08-10,H-1B,15-1211.00,Computer Systems Analysts,Y,2022-08-08,2025-08-07,...,NaN,NaN,1,Yes,Yes,No,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business
9,Withdrawn,2023-09-30,2023-09-30,NaT,E-3 Australian,11-1021.00,General and Operations Managers,Y,2023-12-16,2025-12-15,...,NaN,NaN,2,Yes,NaN,NaN,NaN,NaN,NaN,Disclose Business
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127930,Certified - Withdrawn,2023-04-12,2023-07-02,2023-04-19,H-1B,17-2071.00,Electrical Engineers,Y,2023-05-01,2026-04-30,...,NaN,NaN,2,Yes,No,No,NaN,NaN,NaN,Disclose Business
127931,Certified - Withdrawn,2020-04-06,2023-07-02,2020-04-13,H-1B,17-2071.00,Electrical Engineers,Y,2020-10-01,2023-10-01,...,NaN,NaN,1,Yes,No,No,NaN,NaN,NaN,Disclose Business
127933,Withdrawn,2023-07-01,2023-07-02,NaT,E-3 Australian,13-1199.00,"Business Operations Specialists, All Other",Y,2023-07-24,2025-07-23,...,NaN,NaN,1,Yes,NaN,NaN,NaN,NaN,NaN,Disclose Business and Employment
127937,Certified - Withdrawn,2021-07-30,2023-07-01,2021-08-06,H-1B,15-1132.00,"Software Developers, Applications",Y,2021-08-16,2024-08-15,...,NaN,NaN,3,Yes,No,No,NaN,NaN,NaN,Disclose Business
127938,Certified - Withdrawn,2021-07-13,2023-07-01,2021-07-20,H-1B,15-1132.00,"Software Developers, Applications",Y,2021-08-16,2024-08-15,...,NaN,NaN,2,Yes,No,No,NaN,NaN,NaN,Disclose Business

In [ ]:
df.to_csv("filtered_h1b.csv")